In [ ]:
def nth_root(n):
    def actual_root(x):
        root = x ** (1/n)
        return root
    return actual_root
print(nth_root(3)(27))

In [ ]:
def add_zeros(string):
    """Returns a string padded with zeros
       to ensure consistent length"""
    updated_string = string + '0'
    def add_more():
        """Adds more zeros if necessary"""
        nonlocal updated_string
        updated_string = updated_string + '0'
    while len(updated_string) < 6:
        add_more()
    return updated_string
(add_zeros('3.4'), add_zeros('5.678'))

In [ ]:
x = ['aPPle', 'baNANa']
def caps (li):
    """"Returns a list, with all elements capitalized"""
    def inner (w):
        """Returns a capitalized word"""
        return w.capitalize()
    return ([inner(li[0]), inner(li[1])])
print(caps(x))

In [ ]:
from functools import reduce
product = [1, 3, 2]
result =reduce(lambda x, y: x * y, product)
print(result)

In [ ]:
def easy_print(**x):
        for key, value in x.items():
            print('The value of ' + 
                  str(key) + " is " + 
                  str(value))
(easy_print(a = 10), easy_print(b = 12))

In [ ]:
def mean(*args):
    """Returns the mean of all the numbers"""
    total_sum = 0 # Intial sum
    n = len(args) # Number of arguments
    for x in args:
        total_sum = total_sum + x
    return total_sum/n
print((mean(3, 4), mean(20, 25, 30)))

In [ ]:
def check_type(**kwargs):
    return type(kwargs)

check_type(a = 1, b = 2, c = 3)

In [ ]:
def sorted_elements(x, desc=True, n=2):
    new_x = sorted(x, reverse=desc)[0:n]
    return new_x

In [ ]:
def check_type(*args):
    return type(args)

check_type(1, 2, 3)

In [ ]:
characters_names = ['Felicity Smoak', 'Laurel Lance']
code_names = ['Overwatch', 'Black Canary']


In [2]:
def convert_yards(y, feet = True):
    if feet is True:
        new_y = y * 3
    else:
        new_y = y * 36
    return new_y
print(convert_yards(10))

30


In [17]:
def mean (list(x)):
    """Returns the mean of all the numbers"""
    total_sum = 0
    n = len(x)
    for i in x:
        total_sum = total_sum + i
    return total_sum/n
print((mean(4, 5), mean(40, 45, 50)))

SyntaxError: invalid syntax (3862606972.py, line 1)

In [21]:
def add_zeros(string):
    """Returns a string padded with zeros
       to ensure consistent length"""
    updated_string = string + '0'
    def add_more():
        """Adds more zeros if necessary"""
        nonlocal updated_string
        updated_string = updated_string + '0'
    while len(updated_string) < 6:
        add_more()
    return updated_string
(add_zeros('1.2'), add_zeros('45.67'))

('1.2000', '45.670')

In [23]:
x = [3, -1, -10, 2, 7]
greater_than_zero = filter(lambda n: n > 0, x)
print(list(greater_than_zero))

[3, 2, 7]


In [24]:
def sorted_elements(x, desc=True, n=2):
    new_x = sorted(x, reverse=desc)[0:n]
    return new_x
a = [0, 6, 11, 1, 0, 10]
print(sorted_elements(a, n=3))

[11, 10, 6]


In [25]:
def nth_root(n):
    def actual_root(x):
        root = x ** (1/n)
        return root
    return actual_root
print(nth_root(3)(27))

3.0


In [26]:
def convert_yards(y, feet = True):
    if feet is True:
        new_y = y * 3
    else:
        new_y = y * 36
    return new_y
print(convert_yards(10))

30


In [28]:
def money_off (discount,coupon):
  """Returns the final price paid after the discount (float < 0.5) and coupon (int < 40) have been applied."""
  full_price = 100
  discount_diff = 1 - discount
  discounted = full_price * discount_diff
  final_price = discounted - coupon
  print(final_price)
money_off(.2,5)

75.0


In [30]:
import numpy as np
x = np.array([[1, 2, 7],
              [7, 7, 1]])
y = np.array([[6, 5, 5], 
              [0, 6, 1]])
print(x*y,x+y)

[[ 6 10 35]
 [ 0 42  1]] [[ 7  7 12]
 [ 7 13  2]]


In [32]:
list = [1,2,3,-2,-6,-4,5]
list.index(3)

2

In [33]:
x = [9, 2, 8, 4, 5]
x.remove(5)
print(x)

[9, 2, 8, 4]


In [37]:
ages=np.array([21, 17, 65, 43, 29, 50, 35])
print(ages)
ages[ages>45]

[21 17 65 43 29 50 35]


array([65, 50])

In [39]:
rgb=([[[255,   0,   0],
        [  0,   0,   0],
        [  0,   0, 255]],

       [[255,   0, 255],
        [255, 255, 255],
        [255, 255,   0]]])
print(np.flip(rgb, axis=(1, 2)))

[[[255   0   0]
  [  0   0   0]
  [  0   0 255]]

 [[  0 255 255]
  [255 255 255]
  [255   0 255]]]


In [40]:
array=([[ 5,  1,  3,  2,  4,  6],
       [ 5,  8,  0,  3,  1,  2],
       [ 3, 10,  6, 21, 15,  1]])
print(array[array>7])

TypeError: '>' not supported between instances of 'list' and 'int'

In [42]:
arr=np.array([[ 1,  2,  3,  4,  5,  6],
       [ 0,  1,  2,  3,  5,  8],
       [ 1,  3,  6, 10, 15, 21]])
print(arr[:,0:7:3])

[[ 1  4]
 [ 0  3]
 [ 1 10]]


In [43]:
x = 4
print(x % 7 + 6)

10


In [44]:
p = 8
q = 4
print(p - q)

4


In [48]:
import numpy as np
store = np.array([7, 8, 4, 6])
cost  = np.array([76, 87, 68, 88])
np_cols = np.column_stack((store, cost))
print(np_cols)

[[ 7 76]
 [ 8 87]
 [ 4 68]
 [ 6 88]]


In [50]:
print(np.array([0, True, "python"]))

['0' 'True' 'python']


In [51]:
fg=np.array([[ 1,  2,  3,  4,  5,  6],
       [ 0,  1,  2,  3,  5,  8],
       [ 1,  3,  6, 10, 15, 21]])
print(fg[:2, :2])

[[1 2]
 [0 1]]


In [54]:
help(np.ndarray.reshape)

Help on method_descriptor:

reshape(...)
    a.reshape(shape, order='C')
    
    Returns an array containing the same data with a new shape.
    
    Refer to `numpy.reshape` for full documentation.
    
    See Also
    --------
    numpy.reshape : equivalent function
    
    Notes
    -----
    Unlike the free function `numpy.reshape`, this method on `ndarray` allows
    the elements of the shape parameter to be passed in as separate arguments.
    For example, ``a.reshape(10, 11)`` is equivalent to
    ``a.reshape((10, 11))``.

